#!/usr/bin/env python3
"""Prepare refinement PR artifacts from a strategy and its review.

Deterministically splits a strategy file into three outputs for the
refinement PR workflow:

1. **Committed file** — the strategy content (the HOW), for staff
   engineers to edit directly in the PR.
2. **PR body** — metadata, review summary, and business context
   (the WHY), shown in the PR description.
3. **Process gates** — the Prerequisites & Process Gates table,
   posted as a PR review comment.

Usage:
    python3 scripts/prepare_refinement_pr.py \\
        artifacts/strat-tasks/RHAISTRAT-1182.md \\
        artifacts/strat-reviews/RHAISTRAT-1182-review.md \\
        --out-doc /tmp/strat-refinement-RHAISTRAT-1182.md \\
        --out-body /tmp/strat-refinement-RHAISTRAT-1182-body.md \\
        --out-gates /tmp/strat-refinement-RHAISTRAT-1182-gates.md
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from artifact_utils import read_frontmatter, read_frontmatter_validated


JIRA_BASE = "https://redhat.atlassian.net/browse"

STRATEGY_HEADING_RE = re.compile(
    r"^## Strategy(\s.*)?$", re.MULTILINE
)
PROCESS_GATES_HEADING_RE = re.compile(
    r"^### Prerequisites & Process Gates\s*$", re.MULTILINE
)
STAFF_ENGINEER_HEADING_RE = re.compile(
    r"^## Staff Engineer Input\s*$", re.MULTILINE
)


def _score_status(score):
    if score >= 2:
        return "✓"
    if score == 1:
        return "⚠"
    return "✗"


def _parse_score_notes(review_body):
    """Extract per-dimension notes from the ``## Scores`` table."""
    notes = {}
    in_table = False
    for line in review_body.split("\n"):
        if line.strip().startswith("## Scores"):
            in_table = True
            continue
        if in_table and line.startswith("## "):
            break
        if not in_table or not line.startswith("|"):
            continue
        if line.startswith("|--") or line.startswith("| --"):
            continue
        cells = [c.strip() for c in line.split("|")]
        cells = [c for c in cells if c]
        if len(cells) < 3:
            continue
        label = cells[0].strip("*").strip()
        if label in ("Criterion", "Total"):
            continue
        notes[label.lower()] = cells[2]
    return notes


def _split_at_strategy(body):
    """Split body at the ``## Strategy`` heading.

    Handles both ``## Strategy`` and the legacy
    ``## Strategy (AI Generated by Agentic SDLC Pipeline)`` form.
    Returns ``(business_need, strategy_content)``; exits on failure.
    """
    match = STRATEGY_HEADING_RE.search(body)
    if not match:
        return body, None
    return body[: match.start()].rstrip(), body[match.start() :].strip()


def _extract_process_gates(content):
    """Remove the ``### Prerequisites & Process Gates`` section.

    Returns ``(content_without_gates, gates_section_or_None)``.
    """
    match = PROCESS_GATES_HEADING_RE.search(content)
    if not match:
        return content, None

    start = match.start()
    rest = content[match.end() :]
    # Stop at the next ## or ### heading
    next_heading = re.search(r"^###?\s", rest, re.MULTILINE)
    end = match.end() + next_heading.start() if next_heading else len(content)

    extracted = content[start:end].strip()
    before = content[:start].rstrip()
    after = content[end:].lstrip("\n")
    remaining = before + "\n\n" + after if after else before
    return remaining, extracted


def _strip_staff_engineer_input(content):
    """Remove ``## Staff Engineer Input`` and everything after it."""
    match = STAFF_ENGINEER_HEADING_RE.search(content)
    if match:
        return content[: match.start()].rstrip()
    return content


def _normalize_strategy_heading(content):
    """Replace any variant of the heading with plain ``## Strategy``."""
    return STRATEGY_HEADING_RE.sub("## Strategy", content, count=1)


# Legacy disclaimer comments to strip from existing strategy files.
_LEGACY_COMMENTS = [
    re.compile(
        r"^<!-- DO NOT manually modify this section\..*-->\s*\n?",
        re.MULTILINE,
    ),
    re.compile(
        r"^<!-- To provide corrections, edit the Feature Refinement PR.*-->\s*\n?",
        re.MULTILINE,
    ),
]


def _strip_legacy_comments(content):
    """Remove pipeline disclaimer comments from pre-update strategy files."""
    for pattern in _LEGACY_COMMENTS:
        content = pattern.sub("", content)
    return content


def prepare(task_file, review_file, out_doc, out_body, out_gates):
    task_fm, task_body = read_frontmatter(task_file)
    if not task_fm:
        print(f"ERROR: No frontmatter in {task_file}", file=sys.stderr)
        sys.exit(1)

    review_fm, review_body = read_frontmatter_validated(review_file, "strat-review")

    strat_id = task_fm["strat_id"]
    title = task_fm.get("title", "")
    source_rfe = task_fm.get("source_rfe", "")
    jira_key = task_fm.get("jira_key", strat_id)
    priority = task_fm.get("priority", "")
    status = task_fm.get("status", "")

    jira_url = f"{JIRA_BASE}/{jira_key}" if jira_key else ""
    rfe_url = f"{JIRA_BASE}/{source_rfe}" if source_rfe else ""

    scores = review_fm.get("scores", {})
    recommendation = review_fm.get("recommendation", "").upper()
    total = scores.get("total", 0)

    score_notes = _parse_score_notes(review_body)

    # --- Split ---
    business_need, strategy_content = _split_at_strategy(task_body)
    if strategy_content is None:
        print(
            f"ERROR: No '## Strategy' heading found in {task_file}",
            file=sys.stderr,
        )
        sys.exit(1)

    strategy_content = _normalize_strategy_heading(strategy_content)
    strategy_content = _strip_legacy_comments(strategy_content)
    strategy_content, gates_content = _extract_process_gates(strategy_content)
    strategy_content = _strip_staff_engineer_input(strategy_content)

    # --- PR body ---
    lines = [
        f"**Strategy**: {strat_id} | "
        f"**Source RFE**: [{source_rfe}]({rfe_url}) | "
        f"**Jira**: [{jira_key}]({jira_url})",
        f"**Title**: {title}",
        f"**Priority**: {priority} | **Status**: {status}",
        "",
        f"# Review Summary — {strat_id}",
        "",
        f"**Verdict**: {recommendation} ({total}/8)",
        "",
        "| Criterion | Score | Status |",
        "|-----------|-------|--------|",
    ]
    for dim in ("feasibility", "testability", "scope", "architecture"):
        s = scores.get(dim, 0)
        lines.append(f"| {dim.title()} | {s}/2 | {_score_status(s)} |")
    lines.append("")

    for dim in ("feasibility", "testability", "scope", "architecture"):
        s = scores.get(dim, 0)
        if s < 2 and dim in score_notes:
            lines.append(f"**{dim.title()}:** {score_notes[dim]}")
            lines.append("")

    if business_need.strip():
        lines.append(business_need.strip())
        lines.append("")

    lines.append("---")
    lines.append(
        "> **Instructions**: Edit the strategy document directly "
        "with your corrections and guidance."
    )
    lines.append(
        "> When done, mark this PR as **Ready for Review** "
        "to trigger pipeline re-evaluation."
    )

    pr_body = "\n".join(lines) + "\n"

    # --- Write outputs ---
    for path in (out_doc, out_body, out_gates):
        d = os.path.dirname(path)
        if d:
            os.makedirs(d, exist_ok=True)

    with open(out_doc, "w") as f:
        f.write(strategy_content + "\n")

    with open(out_body, "w") as f:
        f.write(pr_body)

    if gates_content:
        with open(out_gates, "w") as f:
            f.write(gates_content + "\n")
        print(f"OK: {out_doc}, {out_body}, {out_gates}")
    else:
        print(f"OK: {out_doc}, {out_body} (no process gates found)")


def main():
    parser = argparse.ArgumentParser(
        description="Prepare refinement PR artifacts from a strategy "
        "and its review.",
    )
    parser.add_argument("task_file", help="Path to the strategy task file")
    parser.add_argument("review_file", help="Path to the review file")
    parser.add_argument(
        "--out-doc", required=True, help="Output: committed strategy document"
    )
    parser.add_argument(
        "--out-body", required=True, help="Output: PR description body"
    )
    parser.add_argument(
        "--out-gates", required=True, help="Output: process gates content"
    )
    args = parser.parse_args()
    prepare(
        args.task_file,
        args.review_file,
        args.out_doc,
        args.out_body,
        args.out_gates,
    )


if __name__ == "__main__":
    main()
